name: Build and Deploy Code

on: #push #[push, pull_request]
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3